default: &default
  adapter: postgresql
  username: <%= ENV["POSTGRES_USER"]  %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: db
  database: webapp_<%= Rails.env %>
  encoding: unicode

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default